### ISSUE TITLE
Yosys fails to build

### ISSUE THREAD

**Issue by bntmorgan** [sprout-uci/vrased#2]
To get something correctly which builds : 

$ diff yosys-master/passes/cmds/qwp.cc /tmp/qwp.cc 
21a22
> #include "math.h"

**Comment by ivanolive** [comment]
Thank you for reporting this issue.
We have confirmed that Yosis fails to build in some OS distributions (e.g., Ubuntu 18).
We have modified Yosis and Verilog2SMV sources to include math and it should no longer be a problem.
